version: '2'
services:
    laborcliente-app:
        image: laborcliente
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://laborcliente-mariadb:3306/laborcliente
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=laborcliente-elasticsearch:9300
        ports:
            - 8080:8080
    laborcliente-mariadb:
        extends:
            file: mariadb.yml
            service: laborcliente-mariadb
    laborcliente-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: laborcliente-elasticsearch
